export const CAT_BREEDS = [
  'Tabby',
  'Siamese',
  'Maine Coon',
  'Persian',
  'British Shorthair',
  'Russian Blue',
  'Ragdoll',
  'Bengal',
  'Sphynx',
  'Domestic Shorthair',
  'Calico',
  'Tuxedo',
  'Orange Tabby',
  'Scottish Fold',
  'Bombay',
  'Turkish Angora',
  'Birman',
  'Abyssinian',
  'Devon Rex',
  'Cornish Rex',
  'Unknown',
] as const;

export const INSURANCE_PROVIDER_OPTIONS = [
  'ASPCA Pet Health Insurance',
  'Nationwide',
  'Trupanion',
  'Petplan',
  'Embrace',
  'Healthy Paws',
  'Fetch',
  'Pets Best',
  'Lemonade',
  'Prudent Pet',
  'Figo',
  'Other',
] as const;

export const PERSONALITY_TRAIT_OPTIONS = [
  'Affectionate',
  'Independent',
  'Playful',
  'Curious',
  'Shy',
  'Loyal',
  'Lazy',
  'Bold',
  'Social',
  'Gentle',
  'Feisty',
  'Cuddly',
] as const;
